import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/components/navbar";
import { ScreenSizeUpdater } from "@/components/utils/screen-updater";
import { Footer } from "@/components/footer";
import Logo from "@/public/images/favicon.ico";

export const metadata: Metadata = {
  title: "Kiko Survivor",
  description: "Generated by create next app",
  icons: {
    icon: "images/all_logo_gameplus_new.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" />
      <body>
        <ScreenSizeUpdater />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
